### ISSUE TITLE
Microbit documentation issues

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#536]
- [ ] Missing blocks in sig. See https://github.com/Microsoft/pxt-microbit/issues/170 
- [ ]  Need to document animation queues. See https://github.com/Microsoft/pxt-microbit/issues/130
- [ ] Missing cards on Game reference page. See https://github.com/Microsoft/pxt-microbit/issues/128
- [ ] String-style dimensions ("x") can be rendered but not run. See https://github.com/Microsoft/pxt-microbit/issues/96
- [ ] "pin is pressed" API missing in editor and reference > input page. See https://github.com/Microsoft/pxt-microbit/issues/92

**Comment by HelenFoster** [comment]
> Missing cards on Game reference page.

The information I would have liked to be able to find is about the sprite properties. The default value, the range of possible values, what happens if you try to go outside the range, and what they mean. Needs to be easy to find from the 3 property blocks and "create sprite".

* x: range 0-4 (clamped)
* y: range 0-4 (clamped)
* direction: degrees clockwise where 0 is upwards; default 90; range -135 to 180 (?) in multiples of 45 (wrapped)
* brightness: default 255; range 0-255 (clamped)
* blink: 0 means not blinking; otherwise number has something to do with the blink speed?

**Comment by ganicke** [comment]
Property ref pages are now linked up. The topics themselves may need a review later for accuracy.

Re: https://github.com/Microsoft/pxt-microbit/pull/504.

**Comment by abchatra** [comment]
Thanks @ganicke
